# Generated by Django 4.2.10 on 2024-03-04 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentlist',
            old_name='pref_comp',
            new_name='components',
        ),
    ]
